<?php
session_start();
$temp_path=getcwd();
chdir(substr(str_replace("admin","",dirname(__FILE__)),0,-1));
require_once("config.php");
require_once("db/functions.php");
if (has_access($_SERVER['PHP_SELF'],@$_COOKIE['current_user']))
{
  chdir($temp_path);
  require_once("functions.php");
  $sm=create_admin_smarty_obj();
  $sm->assign("adm_path",admin_path);
  $dt=select("config","image_width,image_height");
  $sm->assign("width",$dt[0][0]);
  $sm->assign("height",$dt[0][1]);
  $sm->display("image_dimention.tpl");
  }
else
{
	access_denied();
} 
?>