<?php
session_start();
$temp_path=getcwd();
chdir(substr(str_replace("admin","",dirname(__FILE__)),0,-1));
require_once("config.php");
require_once("db/functions.php");
if (has_access($_SERVER['PHP_SELF'],@$_COOKIE['current_user']))
{
  $user_detail=explode("/",translate_cookie($_COOKIE['current_user']));
  $all_msgs=select("messages","id,from_name,subject,attachment,read_status,sent_date,message","to_user=".$user_detail[2]);
  chdir($temp_path);
  require_once("functions.php");
  $sm=create_admin_smarty_obj();
  $sm->assign("all_msgs",$all_msgs);
  $sm->assign("adm_path",admin_path);
   $sm->assign("site_domain",siteDomain);
  $sm->display("inbox.tpl");
  }
else
{
	access_denied();
}
?>