<?php
session_start();
$temp_path=getcwd();
chdir(substr(str_replace("admin","",dirname(__FILE__)),0,-1));
require_once("config.php");
require_once("db/functions.php");
if (has_access($_SERVER['PHP_SELF'],@$_COOKIE['current_user']))
{
  chdir($temp_path);
  require_once("functions.php");
  $page=select("pages","title,content","id=".$_GET['pid']);
  $sm=create_admin_smarty_obj();
  $sm->assign("adm_path",admin_path);
  $sm->assign("page",$page);
  $sm->assign("page_id",$_GET['pid']);
  $sm->display("edit_page.tpl");
  }
else
{
	access_denied();
} 
?>